### ISSUE TITLE
How to turn on console?

### ISSUE THREAD

**Issue by BreadJS** [nomis/logitech-z906#10]
Hello,

I'm currently working on the ESP32 project for the Z906 to be compatible with home assistant. I'm currently making it work that esp is in between the console and the subwoofer to control it all. Now here is the issue... I cannot figure out how to turn on the console without using an IR LED or soldering a separate cable to the power on switch. Is this even possible at all? If not that I will have to change how to do this. 

Thanks in advance

**Comment by nomis** [comment]
You can make the console power on when power is applied by modifying its firmware: https://github.com/nomis/logitech-z906/blob/main/firmware.rst#automatic-power-on

**Comment by BreadJS** [comment]
Interesting, I did not see that. However, there is small issue, my console does not have these pins on the bottom. I will have to open up the console to see if those pins are there. I do appreciate the comment and I will let you know how to progress goes! :)
