### ISSUE TITLE
How to enable headphone?

### ISSUE THREAD

**Issue by rabbit-aaron** [nomis/logitech-z906#2]
Great project! Thanks for all the insights about the communication protocol! I see in the interface there are headphone pins, but when I connect my headphone to it I don't hear anything. Is there some condition that needs to be met before it starts outputting signals?

**Comment by nomis** [comment]
You need to send commands to the amplifier over the serial connection before it will do anything.

There's a command for enabling the headphone output: https://github.com/nomis/logitech-z906/blob/main/protocol.rst#headphones-connected

**Comment by rabbit-aaron** [comment]
I'll try it out, thank you!
